import type {
  ColorSwatch,
  LanguageGuideItem,
  LogoVariant,
  Scenario,
  TypeHierarchy,
  TypographyStack,
} from "../../lib/types/brand";

export const BRAND_NAME = {
  parent: "Vayasya",
  vertical: "Vayasya Seva",
  full: "Vayasya — Enterprise Workforce Services & Systems",
} as const;

export const VERTICALS = [
  "Vayasya Seva",
  "Vayasya Setu",
  "Vayasya Kaushal",
  "Vayasya Prabandh",
] as const;

export const FONT_STACKS = [
  {
    label: "Primary",
    family: "Hind",
    fallback: ["Noto Sans", "Segoe UI", "sans-serif"],
    usage: "Body copy, UI labels, navigation, and long-form handbook text.",
  },
  {
    label: "Display",
    family: "Hind",
    fallback: ["Noto Sans", "Segoe UI", "sans-serif"],
    usage: "Headlines, section numerals, and key identity lockups.",
  },
  {
    label: "Data Mono",
    family: "JetBrains Mono",
    fallback: ["ui-monospace", "SFMono-Regular", "monospace"],
    usage: "Data tables, identifiers, and revision metadata.",
  },
] as const satisfies readonly TypographyStack[];

export const COLOR_TOKENS = [
  {
    token: "--vy-neutral-0",
    hex: "#FFFFFF",
    role: "Neutral",
    usage: "neutral-0 foundation white",
  },
  {
    token: "--vy-neutral-25",
    hex: "#FCFCFD",
    role: "Neutral",
    usage: "neutral-25 ultra-light background tint",
  },
  {
    token: "--vy-neutral-50",
    hex: "#F8FAFC",
    role: "Neutral",
    usage: "neutral-50 subtle surface tint",
  },
  {
    token: "--vy-neutral-100",
    hex: "#F1F5F9",
    role: "Neutral",
    usage: "neutral-100 muted panels and cards",
  },
  {
    token: "--vy-neutral-200",
    hex: "#E2E8F0",
    role: "Neutral",
    usage: "neutral-200 default borders and separators",
  },
  {
    token: "--vy-neutral-300",
    hex: "#CBD5E1",
    role: "Neutral",
    usage: "neutral-300 elevated border emphasis",
  },
  {
    token: "--vy-neutral-400",
    hex: "#94A3B8",
    role: "Neutral",
    usage: "neutral-400 tertiary text and disabled controls",
  },
  {
    token: "--vy-neutral-500",
    hex: "#64748B",
    role: "Neutral",
    usage: "neutral-500 body-secondary text",
  },
  {
    token: "--vy-neutral-600",
    hex: "#475569",
    role: "Neutral",
    usage: "neutral-600 secondary text and metadata",
  },
  {
    token: "--vy-neutral-700",
    hex: "#334155",
    role: "Neutral",
    usage: "neutral-700 elevated text emphasis",
  },
  {
    token: "--vy-neutral-800",
    hex: "#1E293B",
    role: "Neutral",
    usage: "neutral-800 high-contrast text and dark accents",
  },
  {
    token: "--vy-neutral-900",
    hex: "#0F172A",
    role: "Neutral",
    usage: "neutral-900 primary text and on-brand dark copy",
  },
  {
    token: "--vy-neutral-950",
    hex: "#020617",
    role: "Neutral",
    usage: "neutral-950 deepest contrast edge cases",
  },
  {
    token: "--vy-gold-50",
    hex: "#FFF9E8",
    role: "Gold",
    usage: "gold-50 whisper tint for premium highlights",
  },
  {
    token: "--vy-gold-100",
    hex: "#FDF1CF",
    role: "Gold",
    usage: "gold-100 low-contrast premium backdrop",
  },
  {
    token: "--vy-gold-200",
    hex: "#FAE19E",
    role: "Gold",
    usage: "gold-200 gentle brand highlight",
  },
  {
    token: "--vy-gold-300",
    hex: "#F4CD6D",
    role: "Gold",
    usage: "gold-300 transitional emphasis",
  },
  {
    token: "--vy-gold-400",
    hex: "#EBB74A",
    role: "Gold",
    usage: "gold-400 elevated accents",
  },
  {
    token: "--vy-gold-500",
    hex: "#DAA236",
    role: "Gold",
    usage: "gold-500 master brand fill and highlight surface",
  },
  {
    token: "--vy-gold-600",
    hex: "#B98621",
    role: "Gold",
    usage: "gold-600 hover and active states for brand surfaces",
  },
  {
    token: "--vy-gold-700",
    hex: "#8F6818",
    role: "Gold",
    usage: "gold-700 text and icons on white backgrounds",
  },
  {
    token: "--vy-gold-800",
    hex: "#6A4C12",
    role: "Gold",
    usage: "gold-800 deep supporting accents",
  },
  {
    token: "--vy-gold-900",
    hex: "#48330B",
    role: "Gold",
    usage: "gold-900 high-contrast dark gold controls",
  },
  {
    token: "--vy-gold-950",
    hex: "#2C1F06",
    role: "Gold",
    usage: "gold-950 reserved ultra-dark gold details",
  },
  {
    token: "--vy-seva-50",
    hex: "#FFF6ED",
    role: "Seva",
    usage: "Seva-50 background tint",
  },
  {
    token: "--vy-seva-100",
    hex: "#FFE9D3",
    role: "Seva",
    usage: "Seva-100 soft contextual background",
  },
  {
    token: "--vy-seva-200",
    hex: "#FDCFA8",
    role: "Seva",
    usage: "Seva-200 mild accent support",
  },
  {
    token: "--vy-seva-300",
    hex: "#F9B379",
    role: "Seva",
    usage: "Seva-300 tertiary accent",
  },
  {
    token: "--vy-seva-400",
    hex: "#F38E46",
    role: "Seva",
    usage: "Seva-400 moderate accent",
  },
  {
    token: "--vy-seva-500",
    hex: "#E06C24",
    role: "Seva",
    usage: "Seva-500 strong accent",
  },
  {
    token: "--vy-seva-600",
    hex: "#BA511A",
    role: "Seva",
    usage: "Seva-600 primary Seva action color",
  },
  {
    token: "--vy-seva-700",
    hex: "#8F3F17",
    role: "Seva",
    usage: "Seva-700 high-contrast Seva text/icons",
  },
  {
    token: "--vy-seva-800",
    hex: "#6E3215",
    role: "Seva",
    usage: "Seva-800 deep Seva accents",
  },
  {
    token: "--vy-seva-900",
    hex: "#552811",
    role: "Seva",
    usage: "Seva-900 darkest Seva shade",
  },
  {
    token: "--vy-setu-50",
    hex: "#F4F7FD",
    role: "Setu",
    usage: "Setu-50 background tint",
  },
  {
    token: "--vy-setu-100",
    hex: "#E7EDF8",
    role: "Setu",
    usage: "Setu-100 soft contextual background",
  },
  {
    token: "--vy-setu-200",
    hex: "#CEDAF0",
    role: "Setu",
    usage: "Setu-200 mild accent support",
  },
  {
    token: "--vy-setu-300",
    hex: "#A8BDE4",
    role: "Setu",
    usage: "Setu-300 tertiary accent",
  },
  {
    token: "--vy-setu-400",
    hex: "#7D98D5",
    role: "Setu",
    usage: "Setu-400 moderate accent",
  },
  {
    token: "--vy-setu-500",
    hex: "#5B77C4",
    role: "Setu",
    usage: "Setu-500 consistent digital focus cue",
  },
  {
    token: "--vy-setu-600",
    hex: "#445FA8",
    role: "Setu",
    usage: "Setu-600 primary Setu action color",
  },
  {
    token: "--vy-setu-700",
    hex: "#374B85",
    role: "Setu",
    usage: "Setu-700 high-contrast Setu text/icons",
  },
  {
    token: "--vy-setu-800",
    hex: "#2D3E6C",
    role: "Setu",
    usage: "Setu-800 deep Setu accents",
  },
  {
    token: "--vy-setu-900",
    hex: "#273558",
    role: "Setu",
    usage: "Setu-900 darkest Setu shade",
  },
  {
    token: "--vy-kaushal-50",
    hex: "#F1FAF6",
    role: "Kaushal",
    usage: "Kaushal-50 background tint",
  },
  {
    token: "--vy-kaushal-100",
    hex: "#DBF2E8",
    role: "Kaushal",
    usage: "Kaushal-100 soft contextual background",
  },
  {
    token: "--vy-kaushal-200",
    hex: "#B9E4D1",
    role: "Kaushal",
    usage: "Kaushal-200 mild accent support",
  },
  {
    token: "--vy-kaushal-300",
    hex: "#8CCFB1",
    role: "Kaushal",
    usage: "Kaushal-300 tertiary accent",
  },
  {
    token: "--vy-kaushal-400",
    hex: "#5FB58F",
    role: "Kaushal",
    usage: "Kaushal-400 moderate accent",
  },
  {
    token: "--vy-kaushal-500",
    hex: "#3D966F",
    role: "Kaushal",
    usage: "Kaushal-500 strong accent",
  },
  {
    token: "--vy-kaushal-600",
    hex: "#2E7A58",
    role: "Kaushal",
    usage: "Kaushal-600 primary Kaushal action color",
  },
  {
    token: "--vy-kaushal-700",
    hex: "#256146",
    role: "Kaushal",
    usage: "Kaushal-700 high-contrast Kaushal text/icons",
  },
  {
    token: "--vy-kaushal-800",
    hex: "#204D38",
    role: "Kaushal",
    usage: "Kaushal-800 deep Kaushal accents",
  },
  {
    token: "--vy-kaushal-900",
    hex: "#1B402F",
    role: "Kaushal",
    usage: "Kaushal-900 darkest Kaushal shade",
  },
  {
    token: "--vy-prabandh-50",
    hex: "#F7F8FA",
    role: "Prabandh",
    usage: "Prabandh-50 background tint",
  },
  {
    token: "--vy-prabandh-100",
    hex: "#EDEFF3",
    role: "Prabandh",
    usage: "Prabandh-100 soft contextual background",
  },
  {
    token: "--vy-prabandh-200",
    hex: "#D8DCE4",
    role: "Prabandh",
    usage: "Prabandh-200 mild accent support",
  },
  {
    token: "--vy-prabandh-300",
    hex: "#B8BFCC",
    role: "Prabandh",
    usage: "Prabandh-300 tertiary accent",
  },
  {
    token: "--vy-prabandh-400",
    hex: "#919BAB",
    role: "Prabandh",
    usage: "Prabandh-400 moderate accent",
  },
  {
    token: "--vy-prabandh-500",
    hex: "#6F7A8D",
    role: "Prabandh",
    usage: "Prabandh-500 strong accent",
  },
  {
    token: "--vy-prabandh-600",
    hex: "#556073",
    role: "Prabandh",
    usage: "Prabandh-600 primary Prabandh action color",
  },
  {
    token: "--vy-prabandh-700",
    hex: "#434C5D",
    role: "Prabandh",
    usage: "Prabandh-700 high-contrast Prabandh text/icons",
  },
  {
    token: "--vy-prabandh-800",
    hex: "#353C4A",
    role: "Prabandh",
    usage: "Prabandh-800 deep Prabandh accents",
  },
  {
    token: "--vy-prabandh-900",
    hex: "#2A303C",
    role: "Prabandh",
    usage: "Prabandh-900 darkest Prabandh shade",
  },
  {
    token: "--vy-success",
    hex: "#1F7A4D",
    role: "Semantic",
    usage: "success semantic status",
  },
  {
    token: "--vy-info",
    hex: "#215EA6",
    role: "Semantic",
    usage: "info semantic status",
  },
  {
    token: "--vy-warning",
    hex: "#A45E0C",
    role: "Semantic",
    usage: "warning semantic status",
  },
  {
    token: "--vy-danger",
    hex: "#B42318",
    role: "Semantic",
    usage: "danger semantic status",
  },
  {
    token: "--vy-pending",
    hex: "#556073",
    role: "Semantic",
    usage: "pending semantic status",
  },
  {
    token: "--vy-chart-1",
    hex: "#445FA8",
    role: "Data Visualization",
    usage: "Data-viz sequence 1",
  },
  {
    token: "--vy-chart-2",
    hex: "#2E7A58",
    role: "Data Visualization",
    usage: "Data-viz sequence 2",
  },
  {
    token: "--vy-chart-3",
    hex: "#BA511A",
    role: "Data Visualization",
    usage: "Data-viz sequence 3",
  },
  {
    token: "--vy-chart-4",
    hex: "#6F7A8D",
    role: "Data Visualization",
    usage: "Data-viz sequence 4",
  },
  {
    token: "--vy-chart-5",
    hex: "#A45E0C",
    role: "Data Visualization",
    usage: "Data-viz sequence 5",
  },
  {
    token: "--vy-chart-6",
    hex: "#8F6818",
    role: "Data Visualization",
    usage: "Data-viz sequence 6",
  },
  {
    token: "--vy-chart-7",
    hex: "#7D98D5",
    role: "Data Visualization",
    usage: "Data-viz sequence 7",
  },
  {
    token: "--vy-chart-8",
    hex: "#B9E4D1",
    role: "Data Visualization",
    usage: "Data-viz sequence 8",
  },
  {
    token: "--vy-bg-canvas",
    hex: "#FFFFFF",
    role: "Role Mapping",
    usage: "bg.canvas -> neutral-0",
  },
  {
    token: "--vy-bg-subtle",
    hex: "#F8FAFC",
    role: "Role Mapping",
    usage: "bg.subtle -> neutral-50",
  },
  {
    token: "--vy-bg-muted",
    hex: "#F1F5F9",
    role: "Role Mapping",
    usage: "bg.muted -> neutral-100",
  },
  {
    token: "--vy-border-default",
    hex: "#E2E8F0",
    role: "Role Mapping",
    usage: "border.default -> neutral-200",
  },
  {
    token: "--vy-text-primary",
    hex: "#0F172A",
    role: "Role Mapping",
    usage: "text.primary -> neutral-900",
  },
  {
    token: "--vy-text-secondary",
    hex: "#475569",
    role: "Role Mapping",
    usage: "text.secondary -> neutral-600",
  },
  {
    token: "--vy-brand-primary",
    hex: "#DAA236",
    role: "Role Mapping",
    usage: "brand.primary -> gold-500",
  },
  {
    token: "--vy-brand-primary-hover",
    hex: "#B98621",
    role: "Role Mapping",
    usage: "brand.primary.hover -> gold-600",
  },
  {
    token: "--vy-brand-on-primary",
    hex: "#0F172A",
    role: "Role Mapping",
    usage: "brand.onPrimary -> neutral-900",
  },
  {
    token: "--vy-brand-text",
    hex: "#8F6818",
    role: "Role Mapping",
    usage: "brand.text -> gold-700",
  },
  {
    token: "--vy-focus-ring",
    hex: "#5B77C4",
    role: "Role Mapping",
    usage: "focus.ring -> setu-500",
  },
  {
    token: "--vy-bg",
    hex: "#FFFFFF",
    role: "Compatibility",
    usage: "Legacy alias for background canvas",
  },
  {
    token: "--vy-fg",
    hex: "#0F172A",
    role: "Compatibility",
    usage: "Legacy alias for primary text",
  },
  {
    token: "--vy-text-strong",
    hex: "#0F172A",
    role: "Compatibility",
    usage: "Legacy alias for high-emphasis text",
  },
  {
    token: "--vy-muted",
    hex: "#F1F5F9",
    role: "Compatibility",
    usage: "Legacy alias for muted surfaces",
  },
  {
    token: "--vy-muted-fg",
    hex: "#475569",
    role: "Compatibility",
    usage: "Legacy alias for secondary text",
  },
  {
    token: "--vy-border",
    hex: "#E2E8F0",
    role: "Compatibility",
    usage: "Legacy alias for border default",
  },
  {
    token: "--vy-gold-ui",
    hex: "#DAA236",
    role: "Compatibility",
    usage: "Legacy alias for brand.primary (gold-500)",
  },
  {
    token: "--vy-seva",
    hex: "#BA511A",
    role: "Compatibility",
    usage: "Legacy alias for Seva primary (seva-600)",
  },
  {
    token: "--vy-setu",
    hex: "#445FA8",
    role: "Compatibility",
    usage: "Legacy alias for Setu primary (setu-600)",
  },
  {
    token: "--vy-kaushal",
    hex: "#2E7A58",
    role: "Compatibility",
    usage: "Legacy alias for Kaushal primary (kaushal-600)",
  },
  {
    token: "--vy-prabandh",
    hex: "#556073",
    role: "Compatibility",
    usage: "Legacy alias for Prabandh primary (prabandh-600)",
  },
] as const satisfies readonly ColorSwatch[];

export const LOGO_RULES = {
  lockupHierarchy: {
    parentWordmark: "Vayasya (larger, semibold)",
    verticalWordmark: "Vertical name (smaller, regular or medium)",
  },
  colorControl: [
    "Use source logo asset as supplied.",
    "Do not recolor logo mark or wordmark.",
    "Gold logo appearance is mandatory where the master logo is used.",
  ],
  variants: [
    {
      id: "master-light",
      label: "Master logo on light background",
      filePath: "/brand/logos/master-logo-light.svg",
      background: "light",
      minWidthPx: 120,
      clearSpaceRule: "At least 1x height of the V in Vayasya around all sides.",
    },
    {
      id: "master-dark",
      label: "Master logo on dark background",
      filePath: "/brand/logos/master-logo-dark.svg",
      background: "dark",
      minWidthPx: 120,
      clearSpaceRule: "At least 1x height of the V in Vayasya around all sides.",
    },
  ] as const satisfies readonly LogoVariant[],
  prohibited: [
    "No drop shadows, glow, bevel, or gradient overlays.",
    "No stretching, condensing, skewing, or rotation.",
    "No placing logo over visually busy image regions without a calm plate.",
  ],
} as const;

export const COLOR_USAGE_RULES = [
  {
    context: "Surface composition",
    risk: "Overusing accents reduces readability and weakens brand hierarchy.",
    recommended:
      "Use a 70/20/10 split: 70% neutrals, 20% one vertical or master-brand color, 10% semantic or chart highlights.",
  },
  {
    context: "Vertical-specific documents",
    risk: "Mixing vertical accents can imply wrong business entity ownership.",
    recommended:
      "Use exactly one vertical accent per document unless the content is explicitly multi-vertical and labeled accordingly.",
  },
  {
    context: "Status communication",
    risk: "Using decorative colors for risk/compliance messages can invert meaning.",
    recommended:
      "Use semantic tokens: success, info, warning, danger, and pending for status; do not substitute decorative accents.",
  },
  {
    context: "Brand gold usage",
    risk: "Treating gold as body text or multi-tone decoration can make premium surfaces look dusty.",
    recommended:
      "Use gold-500 for fills/highlights, gold-700 for text/icons on white, and neutral-900 for text on gold backgrounds.",
  },
] as const satisfies readonly Scenario[];

const TYPE_HIERARCHY = [
  {
    level: "Display",
    fontFamily: "Hind",
    fontWeight: 600,
    fontSize: "40px",
    lineHeight: "48px",
    letterSpacing: "0",
    usage: "Top-level page headers and major section titles.",
  },
  {
    level: "H2",
    fontFamily: "Hind",
    fontWeight: 600,
    fontSize: "30px",
    lineHeight: "38px",
    letterSpacing: "0",
    usage: "Section headers and major content blocks.",
  },
  {
    level: "H3",
    fontFamily: "Hind",
    fontWeight: 500,
    fontSize: "24px",
    lineHeight: "32px",
    letterSpacing: "0",
    usage: "Subsections and structured guidance headings.",
  },
  {
    level: "Body",
    fontFamily: "Hind",
    fontWeight: 400,
    fontSize: "18px",
    lineHeight: "30px",
    letterSpacing: "0",
    usage: "Primary handbook copy and explanatory text.",
  },
  {
    level: "Body Small",
    fontFamily: "Hind",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "26px",
    letterSpacing: "0",
    usage: "Helper notes, captions, and form instructions.",
  },
  {
    level: "Data",
    fontFamily: "JetBrains Mono",
    fontWeight: 500,
    fontSize: "14px",
    lineHeight: "22px",
    letterSpacing: "0",
    usage: "Data tables, IDs, and machine-readable values.",
  },
] as const satisfies readonly TypeHierarchy[];

const LANGUAGE_GUIDE = [
  {
    rule: "Write in active voice with named owner and action.",
    rationale: "Operational text must identify accountability clearly.",
    examples: [
      "Use: The account manager sends the revised scope by 5:00 PM IST.",
      "Avoid: Revised scope will be sent soon.",
    ],
  },
  {
    rule: "Limit sentence length to 22 words unless a legal clause requires more.",
    rationale: "Shorter sentences reduce misinterpretation in client communications.",
    examples: [
      "Use two short sentences for obligation and timeline.",
      "Split long legal context into bullet points with conditions.",
    ],
  },
  {
    rule: "Use India-first formatting for dates, time, and numbers.",
    rationale: "Consistent formatting reduces ambiguity across internal and client teams.",
    examples: [
      "Date: 10 Feb 2026",
      "Time: 17:30 IST",
      "Number grouping: 12,34,567",
    ],
  },
  {
    rule: "Use title case for section headings and sentence case for body labels.",
    rationale: "Predictable capitalization improves scanability in long documents.",
    examples: [
      "Heading: Claims Discipline",
      "Label: Approval owner",
    ],
  },
] as const satisfies readonly LanguageGuideItem[];

export const TYPO_RULES = {
  hierarchy: TYPE_HIERARCHY,
  language: LANGUAGE_GUIDE,
  lineLength: {
    idealBodyCharacters: "55-72 characters per line",
    maxBodyCharacters: "80 characters per line",
    tableCellWrapThreshold: "32-40 characters per cell before wrapping",
  },
  capitalization: {
    headings: "Title Case",
    bodyLabels: "Sentence case",
    acronyms: "Uppercase only when institutionally recognized (GST, SLA, NDA)",
    mixedCaseProhibited: "Do not use random in-word caps for emphasis",
  },
  indiaFirstFormats: {
    datePrimary: "DD MMM YYYY (example: 10 Feb 2026)",
    dateNumeric: "DD/MM/YYYY (example: 10/02/2026)",
    time: "24-hour format with zone (example: 17:30 IST)",
    numberGrouping: "Indian system (example: 12,34,567)",
    currency: "INR with symbol and grouping (example: INR 1,25,000 or Rs 1,25,000)",
    decimalPolicy: "Two decimal places for contractual and finance documents",
  },
} as const;
