import type {
  DownloadableAsset,
  LanguageGuideItem,
  SectionHeader,
  SectionSummaryStrip,
  TypeHierarchy,
  TypographyHierarchyExample,
  TypographyMisuseExample,
  TypographyNeed,
  TypographyQuickAction,
  TypographyReference,
  TypographyRoleAction,
  TypographySpecimenCard,
  TypographyStack,
  TypographySurfaceGuide,
  VisualReferenceLinkMeta,
} from "../../../lib/types/brand";

export const TYPOGRAPHY_SECTION = {
  header: {
    id: "typography",
    number: "07",
    title: "Typography",
    summary: "Use the right type role quickly: Anek for headings, Hind for reading and UI, JetBrains Mono for data.",
  } satisfies SectionHeader,
  summaryStrip: {
    useThisWhen: "You need to choose the right approved type role for a real surface or handoff.",
    doThis: "Pick the approved family by use case, then stay inside the supplied hierarchy and font pack.",
    neverDoThis: "Do not add new fonts, improvise fallbacks, or treat typography as personal styling.",
    whoNeedsThis: "All employees for the quick chooser; deeper detail is for design, product, and engineering.",
  } satisfies SectionSummaryStrip,
  intro:
    "Most people only need to choose the right family role, use the approved pack, and avoid the few failures that make typography look improvised.",
  referenceHref: "/visual/typography",
  referenceTitle: "Open full typography reference",
  referenceAudience: "Design, product, and engineering teams",
  employeeDefaults: [
    "If you are working in a template, do not change the font system.",
    "If typography looks wrong, escalate the asset or rendering issue instead of repairing it locally.",
    "Use the approved family roles as an operating default, not a design playground.",
  ],
  quickActions: [
    {
      id: "font-pack",
      title: "Download font pack",
      description: "Use the approved Anek, Hind, and JetBrains Mono files for brand, product, and document work.",
      href: "/api/brand/font-pack",
      ctaLabel: "Get font pack",
      icon: "download",
      download: true,
      badge: "Authorized teams",
    },
    {
      id: "ui-product",
      title: "Need UI or product typography",
      description: "Jump to the product and interface guidance before introducing headings, labels, or fallback decisions.",
      href: "/visual/typography#surface-chooser",
      ctaLabel: "Open UI guidance",
      icon: "interface",
      badge: "Product / UI",
    },
    {
      id: "data-styling",
      title: "Need table or data styling",
      description: "Use the approved data-role guidance for reports, operational tables, identifiers, and precision-heavy interfaces.",
      href: "/visual/typography#surface-chooser",
      ctaLabel: "Open data guidance",
      icon: "data",
      badge: "Tables / IDs / reports",
    },
    {
      id: "review-check",
      title: "Need review checklist",
      description: "Use the release checks before approving typography in a deck, UI, export, or branded deliverable.",
      href: "/visual/typography#review-technical-notes",
      ctaLabel: "Open review checklist",
      icon: "review",
      badge: "Reviewer path",
    },
  ] satisfies readonly TypographyQuickAction[],
  specimenCards: [
    {
      id: "anek",
      title: "Anek",
      family: "Display family",
      fontClass: "font-display",
      previewLabel: "Headings and high-emphasis hierarchy",
      previewText: "Compliance-first industrial services",
      previewDetail: "Use for hero lines, slide headlines, and section titles that need brand presence.",
      whenToUse: "Page titles, hero headings, deck headlines, and other high-emphasis display moments.",
      hardRule: "Do not use Anek for long reading paragraphs or dense UI text.",
      badge: "Headings",
    },
    {
      id: "hind",
      title: "Hind",
      family: "Body and UI family",
      fontClass: "font-sans",
      previewLabel: "Reading, labels, and interface copy",
      previewText:
        "Use Hind for the sentences people actually need to read, from emails and proposals to UI labels and helper text.",
      previewDetail: "This is the default family for narrative copy, labels, and calm interface text.",
      whenToUse: "Body copy, labels, UI text, summaries, email-like content, and long-form reading.",
      hardRule: "Do not switch away from Hind locally just because a file or tool is rendering badly.",
      badge: "Body / UI",
    },
    {
      id: "jetbrains-mono",
      title: "JetBrains Mono",
      family: "Data family",
      fontClass: "font-mono",
      previewLabel: "Data, identifiers, and aligned values",
      previewText: "WO-1842   24 technicians   09:30 IST   PPE ok",
      previewDetail: "Use where character distinction, tabular rhythm, and precise scanning matter.",
      whenToUse: "Operational data, reports, IDs, table values, and code-like precision fields.",
      hardRule: "Keep mono out of narrative paragraphs and normal body copy.",
      badge: "Data / IDs",
    },
  ] satisfies readonly TypographySpecimenCard[],
  commonNeeds: [
    {
      need: "Proposal or deck heading",
      useThis: "Anek for the heading, Hind for supporting copy",
      note: "Keep the headline clear and short, then let Hind carry the explanation.",
    },
    {
      need: "Email or document body",
      useThis: "Hind",
      note: "Use the reading family for anything people need to scan or read end to end.",
    },
    {
      need: "Product or UI text",
      useThis: "Hind by default, with Anek reserved for sparse high-emphasis display use",
      note: "Keep dense product flows calm; do not bring display typography into working screens casually.",
    },
    {
      need: "Tables, IDs, and operational data",
      useThis: "JetBrains Mono for the values, Hind for surrounding labels or narrative context",
      note: "Use mono only where alignment and character distinction actually help the user.",
    },
  ] satisfies readonly TypographyNeed[],
  misuseChecks: [
    {
      id: "mono-paragraph",
      title: "Narrative body set in mono",
      previewKind: "mono-paragraph",
      issue: "Mono is for precision, not for reading paragraphs or normal body copy.",
      correction: "Move the paragraph back to Hind and keep mono for the actual data.",
    },
    {
      id: "display-body",
      title: "Long body copy in display type",
      previewKind: "display-body",
      issue: "Display typography loses calm readability when it is forced into long reading blocks.",
      correction: "Reserve Anek for headings and move the paragraph into Hind.",
    },
    {
      id: "all-caps",
      title: "All-caps paragraph block",
      previewKind: "all-caps",
      issue: "All-caps body copy slows scanning and turns helpful text into visual noise.",
      correction: "Use sentence case for normal reading, labels, and interface help text.",
    },
    {
      id: "extra-font",
      title: "Extra local font added",
      previewKind: "extra-font",
      issue: "Ad hoc font additions break consistency across brand, product, and office workflows.",
      correction: "Stay inside Anek, Hind, and JetBrains Mono and escalate rendering issues instead of substituting.",
    },
  ] satisfies readonly TypographyMisuseExample[],
  fontPack: {
    name: "Vayasya Font Pack",
    description: "Approved company font files packaged on demand from server-managed assets.",
    filePath: "/api/brand/font-pack",
    fileType: "ZIP",
    accessNote:
      "This package contains internal-use fonts. Keep distribution restricted to authorized company teams.",
  } satisfies DownloadableAsset,
  stacks: [
    {
      label: "Display",
      family: "Anek",
      fallback: ["Hind", "Noto Sans", "Segoe UI", "sans-serif"],
      usage: "Headings, hero lines, and high-emphasis display hierarchy.",
    },
    {
      label: "Body / UI",
      family: "Hind",
      fallback: ["Noto Sans", "Segoe UI", "sans-serif"],
      usage: "Body copy, labels, interface text, and readable long-form content.",
    },
    {
      label: "Data / Mono",
      family: "JetBrains Mono",
      fallback: ["ui-monospace", "monospace"],
      usage: "Tables, operational data, IDs, and code-like values.",
    },
  ] satisfies readonly TypographyStack[],
  hierarchy: [
    {
      level: "Display",
      fontFamily: "Anek",
      fontWeight: 600,
      fontSize: "40px",
      lineHeight: "48px",
      usage: "Page titles and hero statements",
    },
    {
      level: "H2",
      fontFamily: "Anek",
      fontWeight: 600,
      fontSize: "30px",
      lineHeight: "38px",
      usage: "Section headings and major deck moments",
    },
    {
      level: "Body",
      fontFamily: "Hind",
      fontWeight: 400,
      fontSize: "18px",
      lineHeight: "30px",
      usage: "Primary long-form content and explanatory copy",
    },
    {
      level: "Data",
      fontFamily: "JetBrains Mono",
      fontWeight: 500,
      fontSize: "14px",
      lineHeight: "22px",
      usage: "Data values, table content, and precise identifiers",
    },
  ] satisfies readonly TypeHierarchy[],
  languageControls: [
    {
      rule: "Use sentence case by default.",
      rationale: "Sentence case keeps labels, helper text, and document copy calm and quick to scan.",
      examples: ["Use: Approval owner", "Avoid: APPROVAL OWNER"],
    },
    {
      rule: "Break dense paragraphs before they feel wide or tiring.",
      rationale: "Readable paragraph rhythm matters more than trying to fit everything into one block.",
      examples: ["Split long operational explanations into shorter paragraphs or labeled lines."],
    },
    {
      rule: "Reserve mono for values that need alignment or character distinction.",
      rationale: "Mono adds precision in tables and identifiers, but reduces reading comfort in narrative copy.",
      examples: ["Use mono for work order IDs, counts, timestamps, and table values."],
    },
    {
      rule: "Keep hierarchy jumps deliberate, not decorative.",
      rationale: "One clear display layer and one calm reading layer is easier to scan than multiple styling jumps.",
      examples: ["Use Anek for the heading, then let Hind carry the explanation underneath."],
    },
  ] satisfies readonly LanguageGuideItem[],
  rules: [
    "Do not add a new font or local fallback to fix a surface quickly.",
    "Use Anek only for headings and high-emphasis display moments.",
    "Use Hind for readable body copy, labels, and UI text.",
    "Use JetBrains Mono only for data, IDs, and code-like values where precision matters.",
    "Escalate font loading or rendering issues instead of switching families locally.",
  ],
} as const satisfies {
  header: SectionHeader;
  summaryStrip: SectionSummaryStrip;
  intro: string;
  referenceHref: VisualReferenceLinkMeta["referenceHref"];
  referenceTitle: VisualReferenceLinkMeta["referenceTitle"];
  referenceAudience?: VisualReferenceLinkMeta["referenceAudience"];
  employeeDefaults: readonly string[];
  quickActions: readonly TypographyQuickAction[];
  specimenCards: readonly TypographySpecimenCard[];
  commonNeeds: readonly TypographyNeed[];
  misuseChecks: readonly TypographyMisuseExample[];
  fontPack: DownloadableAsset;
  stacks: readonly TypographyStack[];
  hierarchy: readonly TypeHierarchy[];
  languageControls: readonly LanguageGuideItem[];
  rules: readonly string[];
};

export const TYPOGRAPHY_REFERENCE = {
  specialistQuickActions: [
    {
      id: "get-font-pack",
      title: "Get font pack",
      description: "Download the approved fonts before working in design, product, or implementation files.",
      href: "/api/brand/font-pack",
      ctaLabel: "Download font pack",
      icon: "download",
      download: true,
      badge: "Authorized teams",
    },
    {
      id: "jump-hierarchy",
      title: "Jump to hierarchy",
      description: "Go straight to the specimen-led type scale for headings, body copy, and data roles.",
      href: "#hierarchy-system",
      ctaLabel: "Open hierarchy",
      icon: "hierarchy",
      badge: "Design / docs",
    },
    {
      id: "jump-surface",
      title: "Jump to UI/data guidance",
      description: "Use the surface chooser for product UI, tables, reports, and export workflows.",
      href: "#surface-chooser",
      ctaLabel: "Open surface chooser",
      icon: "interface",
      badge: "Product / engineering",
    },
    {
      id: "review-release",
      title: "Review before release",
      description: "Run the reviewer and technical checks before approving a deck, UI, export, or branded deliverable.",
      href: "#review-technical-notes",
      ctaLabel: "Open review checks",
      icon: "review",
      badge: "Reviewer path",
    },
  ] satisfies readonly TypographyQuickAction[],
  roleActions: [
    {
      role: "Designer",
      summary: "Choose the right pack, then lock the approved hierarchy into decks, documents, and branded surfaces.",
      href: "#hierarchy-system",
      actions: [
        "Use the approved font pack instead of local substitutes.",
        "Pair Anek headlines with Hind body copy for collateral and presentations.",
        "Check misuse examples before release if typography starts looking styled for effect.",
      ],
    },
    {
      role: "Developer",
      summary: "Map the approved families to product surfaces, keep fallbacks controlled, and escalate rendering issues early.",
      href: "#surface-chooser",
      actions: [
        "Default product UI text to Hind and reserve Anek for sparse display moments.",
        "Use JetBrains Mono only where data alignment or character distinction matters.",
        "Do not silently swap in local fallbacks when a font-loading issue appears.",
      ],
    },
    {
      role: "Technical reviewer",
      summary: "Use the reviewer checklist to catch family-role mismatches, inconsistent hierarchy, and release-time font substitutions.",
      href: "#review-technical-notes",
      actions: [
        "Confirm the surface is using only approved families.",
        "Check that long reading text is not set in display or mono families.",
        "Reject exports that hide font substitutions or noisy hierarchy changes.",
      ],
    },
  ] satisfies readonly TypographyRoleAction[],
  surfaceGuides: [
    {
      id: "decks-proposals",
      title: "Decks and proposals",
      fontClass: "font-display",
      sampleText: "Operational clarity without visual noise",
      sampleDetail: "Pair a short Anek heading with Hind for supporting explanation.",
      useThis: "Anek for display headlines, Hind for the body and supporting narrative.",
      note: "This keeps formal collateral readable without flattening the heading hierarchy.",
      hardRule: "Do not turn the entire slide or proposal page into display typography.",
      badge: "Brand collateral",
    },
    {
      id: "website-product-ui",
      title: "Website and product UI",
      fontClass: "font-sans",
      sampleText: "Status update available for review",
      sampleDetail: "Use Hind for nav, labels, helper text, and dense interface reading.",
      useThis: "Hind by default, with Anek used sparingly for hero or sparse headline moments.",
      note: "Dense workflows need calm readability more than brand drama.",
      hardRule: "Do not pull display typography into working UI screens unless the surface is intentionally headline-led.",
      badge: "Product / UI",
    },
    {
      id: "reports-data-views",
      title: "Reports and data views",
      fontClass: "font-mono",
      sampleText: "WO-1842   24 technicians   09:30 IST   Completed",
      sampleDetail: "Use mono for aligned values and identifiers, not for the surrounding explanation.",
      useThis: "JetBrains Mono for values and IDs, Hind for context labels or narrative explanation.",
      note: "Use mono where precise scanning helps the reader distinguish similar characters quickly.",
      hardRule: "Do not set the full report narrative in mono just because the surface includes data.",
      badge: "Data / precision",
    },
    {
      id: "exports-office",
      title: "Exported PDFs and office workflows",
      fontClass: "font-sans",
      sampleText: "Use the approved font files before exporting final documents.",
      sampleDetail: "Keep the same family roles across editable docs and final exported outputs.",
      useThis: "Approved font pack with the same Anek, Hind, and Mono roles used in branded source files.",
      note: "Exports should preserve the same hierarchy instead of silently dropping into office defaults.",
      hardRule: "Do not accept a fallback-ridden export just because the document still opens.",
      badge: "Exports / office",
    },
  ] satisfies readonly TypographySurfaceGuide[],
  hierarchyExamples: [
    {
      id: "display",
      level: "Display",
      fontClass: "font-display",
      specimen: "Compliance-first industrial services",
      fontWeight: 600,
      fontSize: "40px",
      lineHeight: "48px",
      usage: "Page titles and hero statements",
      note: "Keep display text short, intentional, and clearly above the body layer.",
    },
    {
      id: "h2",
      level: "H2",
      fontClass: "font-display",
      specimen: "Scope and compliance controls",
      fontWeight: 600,
      fontSize: "30px",
      lineHeight: "38px",
      usage: "Section headings and major deck transitions",
      note: "Use this level to create structure, not to style every emphasized sentence.",
    },
    {
      id: "body",
      level: "Body",
      fontClass: "font-sans",
      specimen: "Use Hind for the copy people actually need to read fully, from proposals to interfaces.",
      fontWeight: 400,
      fontSize: "18px",
      lineHeight: "30px",
      usage: "Primary long-form content and explanatory copy",
      note: "Readable rhythm matters more than squeezing extra text into the same area.",
    },
    {
      id: "data",
      level: "Data",
      fontClass: "font-mono",
      specimen: "WO-1842 | 24 technicians | 09:30 IST",
      fontWeight: 500,
      fontSize: "14px",
      lineHeight: "22px",
      usage: "Tabular values, IDs, and precise operational data",
      note: "Use only where precision and character distinction materially help the reader.",
    },
  ] satisfies readonly TypographyHierarchyExample[],
  reviewerChecklist: [
    "Confirm the surface is using only Anek, Hind, and JetBrains Mono.",
    "Check that the family matches the role: display for headings, Hind for reading, mono for precision data.",
    "Reject long body copy set in display or mono styles.",
    "Check that the hierarchy feels consistent instead of jumping between decorative sizes and weights.",
    "Reject release assets that substituted fonts silently during export or implementation.",
  ],
  technicalNotes: [
    "Use the approved stacks only and keep product and document typography aligned to the same family roles.",
    "Escalate font loading or rendering issues instead of silently switching to a fallback family.",
    "Use JetBrains Mono only where operational precision, alignment, or character distinction materially matter.",
    "If a surface needs more hierarchy, solve it with the approved scale before introducing new styling ideas.",
  ],
} as const satisfies TypographyReference;
